theme: minima
title: "Another Dimension"
# カスタムCSSの読み込み
sass:
  style: compressed
markdown: kramdown
plugins:
  - jekyll-sass-converter
  - jekyll-assets

# カスタムスタイルの指定
assets:
  css: "assets/css/style.css"
